version: '3.9'
services:
  do-processor:
    image: hra-do-processor:latest
    volumes:
      - type: bind
        source: ./digital-objects
        target: /digital-objects
      - type: bind
        source: ./dist
        target: /dist
