version: '3.9'
services:
  do-processor:
    # image: ghcr.io/hubmapconsortium/hra-do-processor:main # uncomment if using the pre-built container
    # image: hra-do-processor # uncomment if using a locally built container
    build: . # uncomment to build locally on the fly
    volumes:
      - type: bind
        source: ./digital-objects
        target: /digital-objects
      - type: bind
        source: ./dist
        target: /dist
