PREFIX ccf: <http://purl.org/ccf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT
  ?node_id
  ?node_group
  ?node_label
  ?node_mapped_to
  ?ftu_illustration
  ?tissue_label
  ?tissue_mapped_to
  ?organ_label
  ?organ_mapped_to
WHERE {
  ?ftu_illustration_node a ccf:FtuIllustrationNode ;
      ccf:node_name ?node_id ;
      ccf:node_group ?node_group ;
      ccf:representation_of ?biological_concept ;
      ccf:part_of_illustration ?ftu_illustration .

  ?biological_concept rdfs:label ?node_label .

  ?ftu_illustration ccf:representation_of ?organ_concept .
  ?ftu_illustration ccf:ccf_located_in ?parent_organ_concept .

  ?organ_concept rdfs:label ?tissue_label .
  ?organ_concept oboInOwl:id ?tissue_mapped_to .

  ?parent_organ_concept rdfs:label ?organ_label .
  ?parent_organ_concept oboInOwl:id ?organ_mapped_to .

  BIND(?biological_concept AS ?node_mapped_to)
}