PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?sub_graph_str
WHERE {
  ?ontology_id a owl:Ontology ;
      prov:hadMember ?sub_graph

  BIND(STR(?sub_graph) AS ?sub_graph_str)
}